import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Psalms 1 - 150</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    
<main className={styles.main}>
     
      <div className={styles.hero}>
            <h2 className={styles.holy}>THE WORD</h2>
                <h1 className={styles.bible}>
                    <a href="https://the-holy-bible.vercel.app/" target="_blank">OF GOD</a>
                </h1>
        
        <h1 className={styles.title}>
         PSALMS
        </h1>
        
        <div  className={styles.image}>
       <Image
                                src="/psalms.gif"
                                alt="psalm 119 gif"
                                height={900}
                                width={2000}
                                priority
                              />
        </div>                      
       <p className={styles.parables}>Poems or songs of thankfulness, praise, worship and repentance, each one is complete by itself.They show a variety of feeling, emotions, attitudes & interests</p>
 <iframe width="100%" height="300" src="https://www.youtube.com/embed/W02LeLPKduM" title="YouTube video player" frameborder="2" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                   


              <div className={styles.nav}>               
       <a href="https://matthew-coral.vercel.app/">
         <Image className={styles.arrow}
                                src="/chevron-left.svg"
                                alt="Left arrow"
                                height={75}
                                width={75}
                                priority
                              />
       </a>

         <a href="https://gofund.me/a2b590af">
              <Image className={styles.arrow}
                                src="/funding.png"
                                alt="funding-icon"
                                height={75}
                                width={75}
                                priority
                              /> 
       </a>
           
        <a href="https://luke-three.vercel.app/">
           <Image className={styles.arrow}
                                src="/chevron-right.svg"
                                alt="right arrow"
                                 height={75}
                                width={75}
                                priority
                              />
       </a>           
        </div>
   


        

        
       
        <div className={styles.grid}>
        <div className={styles.card}>
            <h2 className={styles.chapter}>PSALM 1 &darr;</h2>
            <p>( A Psalm of David )
Blessed is the one
    who does not walk in step with the wicked
or stand in the way that sinners take
    or sit in the company of mockers,
 but whose delight is in the law of the Lord,
    and who meditates on his law day and night.
 That person is like a tree planted by streams of water,
    which yields its fruit in season
and whose leaf does not wither—
    whatever they do prospers.
    Not so the wicked!
    They are like chaff
    that the wind blows away.
    Therefore the wicked will not stand in the judgment,
    nor sinners in the assembly of the righteous.
    For the Lord watches over the way of the righteous,
    but the way of the wicked leads to destruction.</p>
              </div>

<div className={styles.card}>
            <h2 className={styles.chapter}>PSALM 2 &darr;</h2>
            <p>( A Psalm of David )
 Why do the nations conspire[a]
    and the peoples plot in vain?
 The kings of the earth rise up
    and the rulers band together
    against the Lord and against his anointed, saying,
 “Let us break their chains
    and throw off their shackles.”

 The One enthroned in heaven laughs;
    the Lord scoffs at them.
 He rebukes them in his anger
    and terrifies them in his wrath, saying,
 “I have installed my king
    on Zion, my holy mountain.”

 I will proclaim the Lord’s decree:

He said to me, “You are my son;
    today I have become your father.
 Ask me,
    and I will make the nations your inheritance,
    the ends of the earth your possession.
 You will break them with a rod of iron;
    you will dash them to pieces like pottery.”

 Therefore, you kings, be wise;
    be warned, you rulers of the earth.
 Serve the Lord with fear
    and celebrate his rule with trembling.
 Kiss his son, or he will be angry
    and your way will lead to your destruction,
for his wrath can flare up in a moment.
    Blessed are all who take refuge in him.            </p>
              </div>

<div className={styles.card}>
            <h2 className={styles.chapter}>PSALM 3 &darr;</h2>
            <p>( A Psalm of David )
(when he fled from his son Absolam)
Lord, how many are my foes!
    How many rise up against me!
 Many are saying of me,
    “God will not deliver him.”

 But you, Lord, are a shield around me,
    my glory, the One who lifts my head high.
 I call out to the Lord,
    and he answers me from his holy mountain.

 I lie down and sleep;
    I wake again, because the Lord sustains me.
 I will not fear though tens of thousands
    assail me on every side.

 Arise, Lord!
    Deliver me, my God!
Strike all my enemies on the jaw;
    break the teeth of the wicked.

 From the Lord comes deliverance.
    May your blessing be on your people.

             </p>
              </div>

<div className={styles.card}>
            <h2 className={styles.chapter}>PSALM 4 &darr;</h2>
            <p>( A Psalm of David )
                For the director of music. With stringed instruments. A psalm of David.
                Answer me when I call to you,
    my righteous God.
Give me relief from my distress;
    have mercy on me and hear my prayer.

 How long will you people turn my glory into shame?
    How long will you love delusions and seek false gods?
 Know that the Lord has set apart his faithful servant for himself;
    the Lord hears when I call to him.
 Tremble and do not sin;
    when you are on your beds,
    search your hearts and be silent.
 Offer the sacrifices of the righteous
    and trust in the Lord.

 Many, Lord, are asking, “Who will bring us prosperity?”
    Let the light of your face shine on us.
 Fill my heart with joy
    when their grain and new wine abound.

 In peace I will lie down and sleep,
    for you alone, Lord,
    make me dwell in safety.
            </p>
            </div>

 <div className={styles.card}>
            <h2 className={styles.chapter}>PSALM 5 &darr;</h2>
            <p>( A Psalm of David )
                For the director of music. For pipes. A psalm of David.
 Listen to my words, Lord,
    consider my lament.
 Hear my cry for help,
    my King and my God,
    for to you I pray.

 In the morning, Lord, you hear my voice;
    in the morning I lay my requests before you
    and wait expectantly.
 For you are not a God who is pleased with wickedness;
    with you, evil people are not welcome.
 The arrogant cannot stand
    in your presence.
You hate all who do wrong;
     you destroy those who tell lies.
The bloodthirsty and deceitful
    you, Lord, detest.
 But I, by your great love,
    can come into your house;
in reverence I bow down
    toward your holy temple.

 Lead me, Lord, in your righteousness
    because of my enemies—
    make your way straight before me.
 Not a word from their mouth can be trusted;
    their heart is filled with malice.
Their throat is an open grave;
    with their tongues they tell lies.
 Declare them guilty, O God!
    Let their intrigues be their downfall.
Banish them for their many sins,
    for they have rebelled against you.
 But let all who take refuge in you be glad;
    let them ever sing for joy.
Spread your protection over them,
    that those who love your name may rejoice in you.

 Surely, Lord, you bless the righteous;
    you surround them with your favor as with a shield.
            </p>
            </div>


<div className={styles.card}>
            <h2 className={styles.chapter}>PSALM 6 &darr;</h2>
            <p>( A Psalm of David )
              For the director of music. With stringed instruments. According to sheminith.
 Lord, do not rebuke me in your anger
    or discipline me in your wrath.
 Have mercy on me, Lord, for I am faint;
    heal me, Lord, for my bones are in agony.
 My soul is in deep anguish.
    How long, Lord, how long?

 Turn, Lord, and deliver me;
    save me because of your unfailing love.
 Among the dead no one proclaims your name.
    Who praises you from the grave?

 I am worn out from my groaning.

All night long I flood my bed with weeping
    and drench my couch with tears.
    My eyes grow weak with sorrow;
    they fail because of all my foes.

 Away from me, all you who do evil,
    for the Lord has heard my weeping.
 The Lord has heard my cry for mercy;
    the Lord accepts my prayer.
 All my enemies will be overwhelmed with shame and anguish;
    they will turn back and suddenly be put to shame.
            </p>
        </div>
 
 <div className={styles.card}>
            <h2 className={styles.chapter}>PSALM 7 &darr;</h2>
            <p>( A shiggaion of David )
            which he sang to the Lord concerning Cush, a Benjamite.
 Lord my God, I take refuge in you;
    save and deliver me from all who pursue me,
 or they will tear me apart like a lion
    and rip me to pieces with no one to rescue me.

 Lord my God, if I have done this
    and there is guilt on my hands—
 if I have repaid my ally with evil
    or without cause have robbed my foe—
 then let my enemy pursue and overtake me;
    let him trample my life to the ground
    and make me sleep in the dust.[c]

 Arise, Lord, in your anger;
    rise up against the rage of my enemies.
    Awake, my God; decree justice.
 Let the assembled peoples gather around you,
    while you sit enthroned over them on high.
     Let the Lord judge the peoples.
Vindicate me, Lord, according to my righteousness,
    according to my integrity, O Most High.
 Bring to an end the violence of the wicked
    and make the righteous secure—
you, the righteous God
    who probes minds and hearts.

 My shield is God Most High,
    who saves the upright in heart.
 God is a righteous judge,
    a God who displays his wrath every day.
 If he does not relent,
    he will sharpen his sword;
    he will bend and string his bow.
 He has prepared his deadly weapons;
    he makes ready his flaming arrows.

 Whoever is pregnant with evil
    conceives trouble and gives birth to disillusionment.
 Whoever digs a hole and scoops it out
    falls into the pit they have made.
 The trouble they cause recoils on them;
    their violence comes down on their own heads.

 I will give thanks to the Lord because of his righteousness;
    I will sing the praises of the name of the Lord Most High.
            </p>
        </div>
 
       <div className={styles.card}>
            <h2 className={styles.chapter}>PSALM 8 &darr;</h2>
            <p>( A Psalm of David )
                  For the director of music. According to gittith. A psalm of David.
 Lord, our Lord,
    how majestic is your name in all the earth!

You have set your glory
    in the heavens.
 Through the praise of children and infants
    you have established a stronghold against your enemies,
    to silence the foe and the avenger.
 When I consider your heavens,
    the work of your fingers,
the moon and the stars,
    which you have set in place,
 what is mankind that you are mindful of them,
    human beings that you care for them?
 You have made them a little lower than the angels
    and crowned them with glory and honor.
 You made them rulers over the works of your hands;
    you put everything under their feet:
 all flocks and herds,
    and the animals of the wild,
 the birds in the sky,
    and the fish in the sea,
    all that swim the paths of the seas.

 Lord, our Lord,
    how majestic is your name in all the earth!"


            </p>
      </div>
 <div className={styles.card}>
            <h2 className={styles.chapter}>PSALM 9 &darr;</h2>
            <p>( A Psalm of David )
                  For the director of music. To the tune of “The Death of the Son.” A psalm of David.
 I will give thanks to you, Lord, with all my heart;
    I will tell of all your wonderful deeds.
 I will be glad and rejoice in you;
    I will sing the praises of your name, O Most High.

 My enemies turn back;
    they stumble and perish before you.
 For you have upheld my right and my cause,
    sitting enthroned as the righteous judge.
 You have rebuked the nations and destroyed the wicked;
    you have blotted out their name for ever and ever.
 Endless ruin has overtaken my enemies,
    you have uprooted their cities;
    even the memory of them has perished.

 The Lord reigns forever;
    he has established his throne for judgment.
 He rules the world in righteousness
    and judges the peoples with equity.
 The Lord is a refuge for the oppressed,
    a stronghold in times of trouble.
  Those who know your name trust in you,
    for you, Lord, have never forsaken those who seek you.

 Sing the praises of the Lord, enthroned in Zion;
    proclaim among the nations what he has done.
 For he who avenges blood remembers;
    he does not ignore the cries of the afflicted.

 Lord, see how my enemies persecute me!
    Have mercy and lift me up from the gates of death,
 that I may declare your praises
    in the gates of Daughter Zion,
    and there rejoice in your salvation.

 The nations have fallen into the pit they have dug;
    their feet are caught in the net they have hidden.
 The Lord is known by his acts of justice;
    the wicked are ensnared by the work of their hands.[c]
 The wicked go down to the realm of the dead,
    all the nations that forget God.
 But God will never forget the needy;
    the hope of the afflicted will never perish.

 Arise, Lord, do not let mortals triumph;
    let the nations be judged in your presence.
Strike them with terror, Lord;
    let the nations know they are only mortal.



            </p>
      </div>

 <div className={styles.card}>
            <h2 className={styles.chapter}>PSALM 10 &darr;</h2>
            <p>
              Why, Lord, do you stand far off?
    Why do you hide yourself in times of trouble?

 In his arrogance the wicked man hunts down the weak,
    who are caught in the schemes he devises.
 He boasts about the cravings of his heart;
    he blesses the greedy and reviles the Lord.
 In his pride the wicked man does not seek him;
    in all his thoughts there is no room for God.
 His ways are always prosperous;
    your laws are rejected by[b] him;
    he sneers at all his enemies.
 He says to himself, “Nothing will ever shake me.”
    He swears, “No one will ever do me harm.”

 His mouth is full of lies and threats;
    trouble and evil are under his tongue.
 He lies in wait near the villages;
    from ambush he murders the innocent.
His eyes watch in secret for his victims;
     like a lion in cover he lies in wait.
He lies in wait to catch the helpless;
    he catches the helpless and drags them off in his net.
 His victims are crushed, they collapse;
    they fall under his strength.
 He says to himself, “God will never notice;
    he covers his face and never sees.”

 Arise, Lord! Lift up your hand, O God.
    Do not forget the helpless.
 Why does the wicked man revile God?
    Why does he say to himself,
    “He won’t call me to account”?
 But you, God, see the trouble of the afflicted;
    you consider their grief and take it in hand.
The victims commit themselves to you;
    you are the helper of the fatherless.
 Break the arm of the wicked man;
    call the evildoer to account for his wickedness
    that would not otherwise be found out.

 The Lord is King for ever and ever;
    the nations will perish from his land.
 You, Lord, hear the desire of the afflicted;
    you encourage them, and you listen to their cry,
 defending the fatherless and the oppressed,
    so that mere earthly mortals
    will never again strike terror.
            </p>
</div>

 <div className={styles.card}>
            <h2 className={styles.chapter}>
 PSALM 11</h2>
<p>
For the director of music. Of David.
1 In the Lord I take refuge.
    How then can you say to me:
    “Flee like a bird to your mountain.
2 For look, the wicked bend their bows;
    they set their arrows against the strings
to shoot from the shadows
    at the upright in heart.
3 When the foundations are being destroyed,
    what can the righteous do?”

4 The Lord is in his holy temple;
    the Lord is on his heavenly throne.
He observes everyone on earth;
    his eyes examine them.
5 The Lord examines the righteous,
    but the wicked, those who love violence,
    he hates with a passion.
6 On the wicked he will rain
    fiery coals and burning sulfur;
    a scorching wind will be their lot.

7 For the Lord is righteous,
    he loves justice;
    the upright will see his face. 
 </p>
</div>
 
      
      <div className={styles.card}>
            <h2 className={styles.chapter}>
      PSALM 12</h2>
              <p>
              For the director of music. According to sheminith. A psalm of David.
              1 Help, Lord, for no one is faithful anymore;
                  those who are loyal have vanished from the human race.
              2 Everyone lies to their neighbor;
                  they flatter with their lips
                  but harbor deception in their hearts.

              3 May the Lord silence all flattering lips
                  and every boastful tongue—
              4 those who say,
                  “By our tongues we will prevail;
                  our own lips will defend us—who is lord over us?”

              5 “Because the poor are plundered and the needy groan,
                  I will now arise,” says the Lord.
                  “I will protect them from those who malign them.”
              6 And the words of the Lord are flawless,
                  like silver purified in a crucible,
                  like gold refined seven times.

              7 You, Lord, will keep the needy safe
                  and will protect us forever from the wicked,
              8 who freely strut about
                  when what is vile is honored by the human race.    
                  </p>
  </div>
    
    
    
    
          <div className={styles.card}>
            <h2 className={styles.chapter}>
      PSALM 13</h2>
                <p>
        For the director of music. A psalm of David.
        1 How long, Lord? Will you forget me forever?
            How long will you hide your face from me?
        2 How long must I wrestle with my thoughts
            and day after day have sorrow in my heart?
            How long will my enemy triumph over me?

        3 Look on me and answer, Lord my God.
            Give light to my eyes, or I will sleep in death,
        4 and my enemy will say, “I have overcome him,”
            and my foes will rejoice when I fall.

        5 But I trust in your unfailing love;
            my heart rejoices in your salvation.
        6 I will sing the Lord’s praise,
            for he has been good to me.  
          </p>
        </div>
</div>
          </div>
</main>
        <p className={styles.description}> 
        <code className={styles.publisher}>
        Coded, Published & Deployed by His servant: Jason Daniel Nutt 
        </code>
        </p>

     

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
