import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    
<main className={styles.main}>
     
      <div className={styles.hero}>
            <h2 className={styles.holy}>THE HOLY</h2>
                <h1 className={styles.bible}>
                    <a href="https://the-holy-bible.vercel.app/" target="_blank">BIBLE</a>
                </h1>
        
        <h1 className={styles.title}>
         PROVERBS
        </h1>
        <div  className={styles.image}>
       <Image
                                src="/139943824-biblical-vector-illustration-series-moses-received-the-ten-commandments.webp"
                                alt="10 CCommandments"
                                height={900}
                                width={2000}
                                priority
                              />
        </div>                      
           <div className={styles.nav}>               
       <a href="https://the-holy-bible.vercel.app/">
           <Image className={styles.arrow}
                                src="/chevron-left.svg"
                                alt="Left arrow"
                                height={25}
                                width={25}
                                priority
                              />
       </a>

         <a href="#PayPalButton">
          
           <Image
                                src="/chevron-down.svg"
                                alt="Donate Button"
                                height={25}
                                width={25}
                                priority
                              />
          
        </a> 
           
           
        <a href="https://mark-alpha.vercel.app/">
             <Image className={styles.arrow}
                                src="/chevron-right.svg"
                                alt="right arrow"
                                 height={25}
                                width={25}
                                priority
                              />
       </a>           
        </div>
   


        

        
       
        <div className={styles.grid}>
       

          </div>
</main>
        <p className={styles.description}> 
        <code className={styles.publisher}>
        Coded, Published & Deployed by His servant: Jason Daniel Nutt 
        </code>
        </p>

     

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
